name: Build and deploy Node.js app to Azure Web App - omniple

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # This single job now handles everything.
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      # Step 1: Check out the repository's code
      - name: 'Checkout Github Action'
        uses: actions/checkout@v4

      # Step 2: Log in to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6C337119523F44098BD2AF588974F419 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E77097AB5991436780EEA554429BB458 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7A9F0CF2ED6746659B5FDBEAD707BDDD }}

      # Step 3: Deploy the source code to Azure Web App
      # Azure will detect the package.json and automatically run 'npm install' and 'npm run build'
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'omniple'
          slot-name: 'Production'
          package: . # Deploy the current directory (your source code)
